version: '3.2'
services:
  serverless:
    build:
      context: ./serverless
      args:
        - AWS_ACCESS_KEY_ID=root
        - AWS_SECRET_ACCESS_KEY=root
    ports:
      - 3000:3000
    restart: on-failure
    tty: true
    stdin_open: true
    volumes:
      - ./serverless:/app
      - node_modules:/app/node_modules
    environment:
      - AWS_DEFAULT_REGION=localhost
      - DMM_API_ID=$DMM_API_ID
      - DMM_AFFILIATE_ID=$DMM_AFFILIATE_ID
      - SLACK_TOKEN=$SLACK_TOKEN
      - SLACK_CHANNEL_ID=$SLACK_CHANNEL_ID_DEV
    command: bash -c "npm install && ./script/create-dynamodb-dev-tables.sh && sls offline -o 0.0.0.0"
    links:
      - dynamodb
  dynamodb:
    image: cnadiminti/dynamodb-local:latest
    ports:
      - 8000:8000
    command: --sharedDb -inMemory
volumes:
  node_modules: