version: '3.2'
services:
  serverless-prod:
    build:
      context: ./serverless
      args:
        - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
        - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    tty: true
    stdin_open: true
    volumes:
      - ./serverless:/app
      - /app/node_modules
    environment:
      - AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
      - DMM_API_ID=$DMM_API_ID
      - DMM_AFFILIATE_ID=$DMM_AFFILIATE_ID
      - SLACK_TOKEN=$SLACK_TOKEN
      - SLACK_CHANNEL_ID=$SLACK_CHANNEL_ID
    command: bash -c "npm install && sls deploy -v -s prod"