version: '3.5'
services:
  serverless-test:
    build:
      context: ./serverless
      args:
        - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
        - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    ports:
      - 3001:3001
    tty: true
    stdin_open: true
    volumes:
      - ./serverless:/app
      - node_modules:/app/node_modules
    env_file: .env.dev
    command: bash -c "npm install && npm test"
    links:
      - dynamodb
  dynamodb:
    image: cnadiminti/dynamodb-local:latest
    ports:
      - 8000:8000
    command: --sharedDb -inMemory
volumes:
  node_modules: