version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Build Docker Image
          command: docker-compose -f docker-compose.test.yml build
      - run:
          name: Run tests
          command: |
            docker-compose -f docker-compose.test.yml run serverless-test bash -c '\
              npm install && \
              npm test'
  deploy:
    machine: true
    steps:
      - checkout
      - run:
          name: Build Docker Image
          command: docker-compose -f docker-compose.prod.yml build
      - run:
          name: Deploy
          command: |
            docker-compose -f docker-compose.prod.yml run serverless-prod bash -c '\
              npm install && \
              sls deploy -v -s prod'

workflows:
  version: 2
  build-test-and-approval-deploy:
    jobs:
      - build
      - hold:
          type: approval
          requires:
            - build
      - deploy:
          requires:
            - hold