version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Build Docker Image
          command: docker-compose -f docker-compose.test.yml build
      - run:
          name: Run tests
           |
            docker-compose run app-servie-name /bin/bash -c '\
              cp .env.example .env && \
              composer install --no-interaction && \
              php artisan key:generate && \
              ./artisan migrate:refresh && \
              ./vendor/bin/phpunit -c phpunit.circle.xml'
          command: |
            docker-compose -f docker-compose.test.yml run serverless-test bash -c '\
              ls -l && \
              npm install && \
              npm test'
  deploy:
    machine: true
    steps:
      - checkout
      - run:
          name: Build Docker Image
          command: docker-compose build
      - run:
          name: Deploy
          command: docker-compose -f docker-compose.prod.yml up
